goals:
 
  - name: "C201A"
    frame_id: "map"
    position: [54.0, 0.0, 0.0]
    orientation: [0.0, 0.0, 1.0, 0.00665814]

  - name: "C202A"
    frame_id: "map"
    position: [44.0, 0.0, 0.0]
    orientation: [0.0, 0.0, 1.0, 0.00665814]

  - name: "C203A"
    frame_id: "map"
    position: [34.0, 0.0, 0.0]
    orientation: [0.0, 0.0, 1.0, 0.00665814]

  - name: "C204A"
    frame_id: "map"
    position: [24.0, 0.0, 0.0]
    orientation: [0.0, 0.0, 1.0, 0.00665814]
  
  - name: "C205A"
    frame_id: "map"
    position: [14.0, 0.0, 0.0]
    orientation: [0.0, 0.0, 1.0, 0.00665814]

  - name: "C206A"
    frame_id: "map"
    position: [4.0, 0.0, 0.0]
    orientation: [0.0, 0.0, 1.0, 0.00665814]

  - name: "Home"
    frame_id: "map"
    position: [-1.0, -0.25, 0.0]
    orientation: [0.0, 0.0, 0.707199, 0.707015]

  - name: "C201B"
    frame_id: "map"
    position: [54.0, 16.0, 0.0]
    orientation: [0.0, 0.0, -1.0, 0.000879004]

  - name: "C202B"
    frame_id: "map"
    position: [44.0, 16.0, 0.0]
    orientation: [0.0, 0.0, -1.0, 0.000879004]

  - name: "C203B"
    frame_id: "map"
    position: [34.0, 16.0, 0.0]
    orientation: [0.0, 0.0, -1.0, 0.000879004]

  - name: "C204B"
    frame_id: "map"
    position: [24.0, 16.0, 0.0]
    orientation: [0.0, 0.0, -1.0, 0.000879004]

  - name: "C205B"
    frame_id: "map"
    position: [14.0, 16.0, 0.0]
    orientation: [0.0, 0.0, -1.0, 0.000879004]

  - name: "C206B"
    frame_id: "map"
    position: [4.0, 16.0, 0.0]
    orientation: [0.0, 0.0, -1.0, 0.000879004]

  - name: "CHL"
    frame_id: "map"
    position: [63.0, 7.0, 0.0]
    orientation: [0.0, 0.0, -1.0, 0.000879004]